## Ordinal Encoding

In [4]:
from sklearn.preprocessing import OrdinalEncoder


data = [["US"], ["UK"], ["NZ"]]
print(data)


# our label features
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
print(result)

[['US'], ['UK'], ['NZ']]
[[2.]
 [1.]
 [0.]]


In [5]:
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
print(result)

[[2.]
 [1.]
 [0.]]


## One-Hot Encoding

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

enc = OneHotEncoder(handle_unknown="ignore")
data = np.asarray([["US"], ["UK"], ["NZ"]])
enc.fit(data)
enc.categories_

onehotlabels = enc.transform(data).toarray()
onehotlabels

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

## Bag of Words
[See more here](https://okan.cloud/posts/2021-04-08-text-vectorization-using-python-term-document-matrix/)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Input data
flits = [
    "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.",
    "No bird soars too high if he soars with his own wings.",
    "A bird does not sing because it has an answer, it sings because it has a song.",
]

In [23]:
flits = [
    "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.",
    "No bird soars too high if he soars with his own wings.",
    "A bird does not sing because it has an answer, it sings because it has a song.",
]

In [35]:
vect = CountVectorizer(binary=True)
vects = vect.fit_transform(flits)

In [41]:
td = pd.DataFrame(vects.todense()).iloc[:5]
td.columns = vect.get_feature_names_out()
count_vect_df = td
term_document_matrix = td.T
term_document_matrix.columns = ["flit_" + str(i) for i in range(1, 4)]
term_document_matrix["total_count"] = term_document_matrix.sum(axis=1)

In [42]:
print(term_document_matrix.drop(columns=["total_count"]).head(10))

         flit_1  flit_2  flit_3
an            0       0       1
answer        0       0       1
because       0       0       1
bird          1       1       1
broken        1       0       0
cannot        1       0       0
die           1       0       0
does          0       0       1
dreams        1       0       0
fast          1       0       0


In [17]:
count_vect_df

an  answer  because  bird  broken  cannot  die  does  dreams  fast  ...   
0   0       0        0     1       1       1    1     0       1     1  ...  \
1   0       0        0     1       0       0    0     0       0     0  ...   
2   1       1        1     1       0       0    0     1       0     0  ...   

   sing  sings  soars  song  that  to  too  winged  wings  with  
0     0      0      0     0     1   1    0       1      0     0  
1     0      0      1     0     0   0    1       0      1     1  
2     1      1      0     1     0   0    0       0      0     0  

[3 rows x 34 columns]

In [18]:
pd.concat([doc, count_vect_df], axis=1)

0  an  answer  because   
0  Hold fast to dreams, for if dreams die, life i...   0       0        0  \
1  No bird soars too high if he soars with his ow...   0       0        0   
2  A bird does not sing because it has an answer,...   1       1        1   

   bird  broken  cannot  die  does  dreams  ...  sing  sings  soars  song   
0     1       1       1    1     0       1  ...     0      0      0     0  \
1     1       0       0    0     0       0  ...     0      0      1     0   
2     1       0       0    0     1       0  ...     1      1      0     1   

   that  to  too  winged  wings  with  
0     1   1    0       1      0     0  
1     0   0    1       0      1     1  
2     0   0    0       0      0     0  

[3 rows x 35 columns]